### PR TITLE
Fix the committee page

### LINKED ISSUE #38: Missized committee photos + text
image

### PR DESCRIPTION
**Pull request by GeekPro101**
Fixes #38 

- Does quite a few other things, just have a play around

### CODE REVIEW

File: src/lib/index.ts [hunk 1]
```diff
@@ -30,11 +30,65 @@ export const preloadOfficerAvatar = (officeTitle: string): void => {
...
 	for (const office of get(officeStore)) {
 		preloadOfficerAvatar(office.title);
 	}
 }
 
+export function sortOfficesByTitle(objects: Office[]): Office[] {
+	const titleOrder = [
+		'President',
+		'Vice-President',
+		'Treasurer',
```
Comment (apple-phi) [inline src/lib/index.ts:44]: Would it be better to have seniority be set by the CMS?

**Comment by apple-phi** [comment]
Will have a proper look at this later

**Comment by GeekPro101** [comment]
@apple-phi lmk on that review, had a thought about setting it CMS side
